// Package store keeps session state in a single SQLite file (WAL mode).
// Hooks write, the CLI/TUI read; there is no daemon between them.
package store

import (
	"database/sql"
	"errors"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	_ "modernc.org/sqlite"
)

// Session statuses.
const (
	Starting = "starting" // spawned by harness, SessionStart not seen yet
	Idle     = "idle"     // waiting for the next prompt
	Working  = "working"  // processing a prompt / running tools
	Waiting  = "waiting"  // blocked on the user (permission, question)
	Ended    = "ended"    // process gone
	Archived = "archived" // stopped by harness, resumable
)

// PendingPrefix marks a placeholder row created before Claude reports its
// real session id; SessionStart in the same tmux pane claims it.
const PendingPrefix = "pending-"

type Session struct {
	ID             string
	Profile        string
	ConfigDir      string
	Cwd            string
	TranscriptPath string
	Name           string // set by the user (harness new -n); wins over Title
	Title          string // AI-generated by Claude Code
	Status         string
	Detail         string
	LastPrompt     string
	LastMessage    string
	TmuxPane       string
	PID            int
	CreatedAt      time.Time
	UpdatedAt      time.Time
	StatusSince    time.Time
	ArchivedAt     time.Time // zero when not archived
}

// Live reports whether the session is supposed to have a running process.
func (s Session) Live() bool {
	return s.Status != Ended && s.Status != Archived
}

type Store struct{ db *sql.DB }

// migrations[i] upgrades user_version i → i+1. Append only; never edit
// a released step (hooks from an older binary may still be running).
var migrations = []string{
	`CREATE TABLE IF NOT EXISTS sessions (
		session_id      TEXT PRIMARY KEY,
		profile         TEXT NOT NULL DEFAULT '',
		config_dir      TEXT NOT NULL DEFAULT '',
		cwd             TEXT NOT NULL DEFAULT '',
		transcript_path TEXT NOT NULL DEFAULT '',
		title           TEXT NOT NULL DEFAULT '',
		status          TEXT NOT NULL,
		detail          TEXT NOT NULL DEFAULT '',
		last_prompt     TEXT NOT NULL DEFAULT '',
		last_message    TEXT NOT NULL DEFAULT '',
		tmux_pane       TEXT NOT NULL DEFAULT '',
		pid             INTEGER NOT NULL DEFAULT 0,
		created_at      INTEGER NOT NULL,
		updated_at      INTEGER NOT NULL,
		status_since    INTEGER NOT NULL,
		archived_at     INTEGER NOT NULL DEFAULT 0
	);
	CREATE INDEX IF NOT EXISTS sessions_pane ON sessions(tmux_pane) WHERE tmux_pane != '';`,
	`ALTER TABLE sessions ADD COLUMN name TEXT NOT NULL DEFAULT '';`,
}

func migrate(db *sql.DB) error {
	var v int
	if err := db.QueryRow(`PRAGMA user_version`).Scan(&v); err != nil {
		return err
	}
	if v > len(migrations) {
		return fmt.Errorf("state.db schema v%d is newer than this binary (v%d)", v, len(migrations))
	}
	for ; v < len(migrations); v++ {
		// Each step in its own transaction (IMMEDIATE via _txlock), re-checking
		// the version so concurrent processes cannot apply a step twice.
		tx, err := db.Begin()
		if err != nil {
			return err
		}
		var cur int
		if err := tx.QueryRow(`PRAGMA user_version`).Scan(&cur); err != nil {
			tx.Rollback()
			return err
		}
		if cur > v {
			tx.Rollback()
			v = cur - 1
			continue
		}
		if _, err := tx.Exec(migrations[v]); err != nil {
			tx.Rollback()
			return fmt.Errorf("migrate to v%d: %w", v+1, err)
		}
		if _, err := tx.Exec(fmt.Sprintf(`PRAGMA user_version = %d`, v+1)); err != nil {
			tx.Rollback()
			return err
		}
		if err := tx.Commit(); err != nil {
			return err
		}
	}
	return nil
}

// Open opens (creating/migrating as needed) the state database. The first
// switch to WAL takes an exclusive lock and can fail with SQLITE_BUSY
// regardless of busy_timeout when several hooks race on a fresh file, so
// busy errors are retried.
func Open(path string) (*Store, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return nil, err
	}
	var err error
	for attempt := range 8 {
		var st *Store
		if st, err = open(path); err == nil {
			return st, nil
		}
		if !isBusy(err) {
			return nil, err
		}
		time.Sleep(time.Duration(10<<attempt) * time.Millisecond / 4)
	}
	return nil, err
}

func isBusy(err error) bool {
	msg := err.Error()
	return strings.Contains(msg, "SQLITE_BUSY") || strings.Contains(msg, "database is locked")
}

func open(path string) (*Store, error) {
	q := url.Values{}
	q.Add("_pragma", "busy_timeout(3000)")
	q.Add("_pragma", "journal_mode(WAL)")
	q.Add("_pragma", "synchronous(NORMAL)")
	q.Add("_txlock", "immediate")
	db, err := sql.Open("sqlite", "file:"+path+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(1)
	if err := migrate(db); err != nil {
		db.Close()
		return nil, err
	}
	return &Store{db: db}, nil
}

func (s *Store) Close() error { return s.db.Close() }

// Tx runs fn in a write transaction (BEGIN IMMEDIATE, so concurrent hooks
// serialise on the lock instead of failing on upgrade).
func (s *Store) Tx(fn func(*Tx) error) error {
	conn, err := s.db.Conn(bgctx)
	if err != nil {
		return err
	}
	defer conn.Close()
	if _, err := conn.ExecContext(bgctx, `BEGIN IMMEDIATE`); err != nil {
		return err
	}
	if err := fn(&Tx{c: conn}); err != nil {
		conn.ExecContext(bgctx, `ROLLBACK`)
		return err
	}
	_, err = conn.ExecContext(bgctx, `COMMIT`)
	return err
}

const cols = `session_id, profile, config_dir, cwd, transcript_path, name, title, status, detail,
	last_prompt, last_message, tmux_pane, pid, created_at, updated_at, status_since, archived_at`

type scanner interface{ Scan(...any) error }

func scan(r scanner) (Session, error) {
	var s Session
	var created, updated, since, archived int64
	err := r.Scan(&s.ID, &s.Profile, &s.ConfigDir, &s.Cwd, &s.TranscriptPath, &s.Name, &s.Title,
		&s.Status, &s.Detail, &s.LastPrompt, &s.LastMessage, &s.TmuxPane, &s.PID,
		&created, &updated, &since, &archived)
	s.CreatedAt = time.Unix(created, 0)
	s.UpdatedAt = time.Unix(updated, 0)
	s.StatusSince = time.Unix(since, 0)
	if archived > 0 {
		s.ArchivedAt = time.Unix(archived, 0)
	}
	return s, err
}

var ErrNotFound = errors.New("session not found")

func (s *Store) List() ([]Session, error) {
	rows, err := s.db.Query(`SELECT ` + cols + ` FROM sessions ORDER BY updated_at DESC`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Session
	for rows.Next() {
		se, err := scan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, se)
	}
	return out, rows.Err()
}

// Find resolves a full id or a unique id prefix (as shown by 'harness ls').
func (s *Store) Find(idOrPrefix string) (Session, error) {
	rows, err := s.db.Query(`SELECT `+cols+` FROM sessions WHERE session_id = ? OR session_id LIKE ? ESCAPE '\' LIMIT 3`,
		idOrPrefix, escapeLike(idOrPrefix)+"%")
	if err != nil {
		return Session{}, err
	}
	defer rows.Close()
	var found []Session
	for rows.Next() {
		se, err := scan(rows)
		if err != nil {
			return Session{}, err
		}
		if se.ID == idOrPrefix {
			return se, nil
		}
		found = append(found, se)
	}
	switch len(found) {
	case 0:
		return Session{}, fmt.Errorf("%w: %s", ErrNotFound, idOrPrefix)
	case 1:
		return found[0], nil
	default:
		return Session{}, fmt.Errorf("ambiguous id prefix %q", idOrPrefix)
	}
}

// PID returns the recorded claude pid of a session, 0 if unknown.
func (s *Store) PID(id string) int {
	var pid int
	s.db.QueryRow(`SELECT pid FROM sessions WHERE session_id = ?`, id).Scan(&pid)
	return pid
}

func escapeLike(s string) string {
	return strings.NewReplacer(`\`, `\\`, `%`, `\%`, `_`, `\_`).Replace(s)
}
